CREATE TABLE TEACHER (
    ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    AGE NUMERIC(3) NOT NULL, -- NUMERIC(3) means INTEGER
    NATIONALITY VARCHAR(2) NOT NULL,
    MEMBERSHIP VARCHAR(1) NOT NULL
);
